# Generated by Django 5.1.7 on 2025-03-19 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenberg_id', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('word_count', models.IntegerField(default=0)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2)),
                ('closeness_centrality', models.FloatField(default=0.0)),
                ('betweenness_centrality', models.FloatField(default=0.0)),
                ('pagerank', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('gutenberg_id',),
            },
        ),
        migrations.CreateModel(
            name='TableJaccard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaccard_similarity', models.DecimalField(decimal_places=4, max_digits=5)),
                ('book1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_book1', to='mygutenberg.booktext')),
                ('book2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_book2', to='mygutenberg.booktext')),
            ],
            options={
                'indexes': [models.Index(fields=['book1', 'book2'], name='mygutenberg_book1_i_b4c763_idx')],
                'unique_together': {('book1', 'book2')},
            },
        ),
        migrations.CreateModel(
            name='TrieNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=1)),
                ('is_end_of_word', models.BooleanField(default=False)),
                ('word_data', models.BinaryField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mygutenberg.trienode')),
            ],
            options={
                'indexes': [models.Index(fields=['parent', 'char'], name='mygutenberg_parent__ed955e_idx')],
                'unique_together': {('parent', 'char')},
            },
        ),
    ]
