# Generated by Django 5.1.7 on 2025-03-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivreEnAnglais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gutenbergID', models.IntegerField(default='-1')),
            ],
            options={
                'ordering': ('gutenbergID',),
            },
        ),
        migrations.CreateModel(
            name='LivreEnFrancais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gutenbergID', models.IntegerField(default='-1')),
            ],
            options={
                'ordering': ('gutenbergID',),
            },
        ),
    ]
