# Generated by Django 5.1.7 on 2025-03-20 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trienode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mygutenberg.trienode'),
        ),
    ]
