# Generated by Django 5.1.7 on 2025-03-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenberg_id', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('gutenberg_id',),
            },
        ),
    ]
