# Generated by Django 5.1.7 on 2025-03-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktext',
            name='pagerank',
        ),
        migrations.AlterField(
            model_name='tablejaccard',
            name='jaccard_similarity',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
