# Generated by Django 5.1.7 on 2025-03-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0002_booktext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktext',
            name='content',
        ),
        migrations.AddField(
            model_name='booktext',
            name='author',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='booktext',
            name='index_table',
            field=models.TextField(blank=True),
        ),
    ]
