# Generated by Django 5.1.7 on 2025-03-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0003_remove_booktext_content_booktext_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvertedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('postings', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booktext',
            name='index_table',
        ),
        migrations.AddField(
            model_name='booktext',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2),
        ),
    ]
