# Generated by Django 5.1.7 on 2025-03-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0003_alter_booktext_title'),
        ('mygutenberg', '0004_recompress_word_data'),
    ]

    operations = [
    ]
