# Generated by Django 5.1.7 on 2025-03-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0004_invertedindex_remove_booktext_index_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LivreEnAnglais',
        ),
        migrations.DeleteModel(
            name='LivreEnFrancais',
        ),
        migrations.RemoveField(
            model_name='booktext',
            name='author',
        ),
        migrations.AddField(
            model_name='booktext',
            name='authors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
