# Generated by Django 5.1.7 on 2025-03-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0005_delete_livreenanglais_delete_livreenfrancais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('index_data', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InvertedIndex',
        ),
    ]
