# Generated by Django 5.1.7 on 2025-03-16 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0006_tableindex_delete_invertedindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableJaccard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaccard_similarity', models.FloatField()),
                ('book1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_book1', to='mygutenberg.booktext')),
                ('book2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_as_book2', to='mygutenberg.booktext')),
            ],
            options={
                'indexes': [models.Index(fields=['book1', 'book2'], name='mygutenberg_book1_i_b4c763_idx')],
                'unique_together': {('book1', 'book2')},
            },
        ),
    ]
