# Generated by Django 5.1.7 on 2025-03-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0007_tablejaccard'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktext',
            name='betweenness_centrality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='booktext',
            name='closeness_centrality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='booktext',
            name='pagerank',
            field=models.FloatField(default=0.0),
        ),
    ]
