# Generated by Django 5.1.7 on 2025-03-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myImageBank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageentry',
            name='created',
        ),
        migrations.AddField(
            model_name='imageentry',
            name='book_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
